name: Services
description: I am services
id: services
attributes:
  - type: text
    id: service-name
    name: Service Name
    description: Write a really cool name please.
    inputs:
      text:
        placeholder: add svc name
  - type: text
    id: service-desciption
    name: Service Desc
    description: Write your brief desciption
    inputs:
      text:
        placeholder: add svc desc
  - type: text
    id: service-url
    name: Service URL
    inputs:
      text:
        placeholder: add svc url
  - type: email
    id: service-email
    name: Service Email
    inputs:
      text:
        placeholder: add svc email
  - type: text
    id: service-image
    name: Service Image
    description: Test image.
    inputs:
      image:
        placeholder: add svc name
